name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golang-${{ runner.os }}
      - name: Setup CI runner
        run: |-
          git config --global --add safe.directory $PWD
          apt-get update
          apt-get install -y --no-install-recommends file
      - name: Execute CI checks
        run: make ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: |
            ${{ github.workspace }}/bin/
          name: binaries
          retention-days: 1
          if-no-files-found: ignore

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup CI runner
        run: |-
          git config --global --add safe.directory $PWD
          apt-get update
          apt-get install -y --no-install-recommends file
      - name: Build release
        run: |-
          git clean -fdx
          mkdir -p bin
          make build-all 2>&1 | tee bin/reproducibility.log
          cd bin; sha256sum * | tee SHA256SUMS
      - uses: softprops/action-gh-release@v2
        with:
          files: bin/*
